<?php 
	$student_data = array(
		'PIP' 		=> $row["PIP"],
		'CI' 		=> $row["CI"],
		'NOMBRES' 	=> $row["NOMBRES"],
		'APELLIDOS' => $row["APELLIDOS"]
	);

	$project_data = array(
		'FECHA DE ENTREGA' 	=> $row["FECHA_DE_ENTREGA"],
		'ASESOR ACADEMICO'	=> $row["ASESOR_ACADEMICO"],
		'ASESOR INDUSTRIAL'	=> $row["ASESOR_INDUSTRIAL"],
		'AREA DE TRABAJO'	=> $row["AREA_DE_TRABAJO"],
		'MODALIDAD' 		=> $row["MODALIDAD"],
		'EMPRESA' 			=> $row["EMPRESA"]
	);
		
	$corrections = array(
		'PRIMERA CORRECCION' 					=> $row["PRIMERA_CORRECCION"],
		'ENTREGA AL DOCENTE 1' 					=> $row["ENTREGA_A_DOCENTE_1"],
		'RECIBIDA DEL DOCENTE 1'				=> $row["RECIBIDA_DEL_DOCENTE_1"],
		'SEGUNDA CORRECCION' 					=> $row["SEGUNDA_CORRECCION"],
		'ENTREGA AL DOCENTE 2' 					=> $row["ENTREGA_AL_DOCENTE_2"],
		'RECIBIDA DEL DOCENTE 2' 				=> $row["RECIBIDA_DEL_DOCENTE_2"],
		'CORRECCION ENTREGADA AL ESTUDIANTE'	=> $row["CORRECCION_ENTREGADA_AL_ESTUDIANTE"],
		'CORRECCION RECIBIDA DEL ESTUDIANTE' 	=> $row["CORRECCION_RECIBIDA_DEL_ESTUDIANTE"]
	);		

	$juries = array(
		'JURADO PRINCIPAL 1' 	=> $row["JURADO_PRINCIPAL_1"],
		'JURADO PRINCIPAL 2' 	=> $row["JURADO_PRINCIPAL_2"],
		'JURADO SUPLENTE 1'		=> $row["JURADO_SUPLENTE_1"],
		'JURADO SUPLENTE 2'		=> $row["JURADO_SUPLENTE_2"]
	);

	$approval = array(
		'APROBADO CTG' 					=> $row["APROBADO_CTG"],
		'ENVIADO A COMISION CENTRAL' 	=> $row["ENVIADO_A_COMISION_CENTRAL"],
		'RECIBIDO DE COMISION CENTRAL'	=> $row["RECIBIDO_DE_COMISION_CENTRAL"]
	);
?>